/** @file */
/*
 * APP test runner
 * Contains all TEST_GROUP_RUNNER definitions for APP tests
 */

#include "ut_common.h"

// APP TEST_GROUP_RUNNER definitions

TEST_GROUP_RUNNER(APP_AES_AEAD_HANDLER) {
    RUN_TEST_CASE(APP_AES_AEAD_HANDLER, missing_msg);
    RUN_TEST_CASE(APP_AES_AEAD_HANDLER, missing_dir);
    RUN_TEST_CASE(APP_AES_AEAD_HANDLER, bad_cipher);
    RUN_TEST_CASE(APP_AES_AEAD_HANDLER, bad_taglen);
    RUN_TEST_CASE(APP_AES_AEAD_HANDLER, bad_aadlen);
    RUN_TEST_CASE(APP_AES_AEAD_HANDLER, bad_gmac);
}

TEST_GROUP_RUNNER(APP_AES_HANDLER) {
    RUN_TEST_CASE(APP_AES_HANDLER, bad_keylen);
    RUN_TEST_CASE(APP_AES_HANDLER, missing_dir);
    RUN_TEST_CASE(APP_AES_HANDLER, bad_cipher);
    RUN_TEST_CASE(APP_AES_HANDLER, bad_mct_dir);
    RUN_TEST_CASE(APP_AES_HANDLER, bad_mct_payloadLen);
}

TEST_GROUP_RUNNER(APP_AES_KW_HANDLER) {
    RUN_TEST_CASE(APP_AES_KW_HANDLER, bad_cipher);
    RUN_TEST_CASE(APP_AES_KW_HANDLER, bad_dir);
    RUN_TEST_CASE(APP_AES_KW_HANDLER, bad_payload);
    RUN_TEST_CASE(APP_AES_KW_HANDLER, bad_key);
}

TEST_GROUP_RUNNER(APP_CMAC_HANDLER) {
    RUN_TEST_CASE(APP_CMAC_HANDLER, missing_msg);
    RUN_TEST_CASE(APP_CMAC_HANDLER, missing_key_aes);
    RUN_TEST_CASE(APP_CMAC_HANDLER, missing_keys_tdes);
    RUN_TEST_CASE(APP_CMAC_HANDLER, disposition_mem_not_allocated);
}

TEST_GROUP_RUNNER(APP_DES_HANDLER) {
    RUN_TEST_CASE(APP_DES_HANDLER, bad_keylen);
    RUN_TEST_CASE(APP_DES_HANDLER, bad_iv);
    RUN_TEST_CASE(APP_DES_HANDLER, missing_dir);
    RUN_TEST_CASE(APP_DES_HANDLER, bad_payload_len);
    RUN_TEST_CASE(APP_DES_HANDLER, bad_cipher);
    RUN_TEST_CASE(APP_DES_HANDLER, bad_tc_initialization);
    RUN_TEST_CASE(APP_DES_HANDLER, null_tc);
    RUN_TEST_CASE(APP_DES_HANDLER, bad_mct_dir);
    RUN_TEST_CASE(APP_DES_HANDLER, bad_mct_payloadLen);
    RUN_TEST_CASE(APP_DES_HANDLER, bad_mct_iv);
}

TEST_GROUP_RUNNER(APP_DRBG_HANDLER) {
    RUN_TEST_CASE(APP_DRBG_HANDLER, bad_cipher);
    RUN_TEST_CASE(APP_DRBG_HANDLER, bad_mode);
    RUN_TEST_CASE(APP_DRBG_HANDLER, bad_alloc_out);
    RUN_TEST_CASE(APP_DRBG_HANDLER, missing_entropy);
    RUN_TEST_CASE(APP_DRBG_HANDLER, no_perso);
}

TEST_GROUP_RUNNER(APP_ECDSA_HANDLER) {
    RUN_TEST_CASE(APP_ECDSA_HANDLER, missing_curve_app);
    RUN_TEST_CASE(APP_ECDSA_HANDLER, missing_hash_alg_app);
    RUN_TEST_CASE(APP_ECDSA_HANDLER, missing_keyver_qx_qy);
    RUN_TEST_CASE(APP_ECDSA_HANDLER, missing_siggen_msg);
    RUN_TEST_CASE(APP_ECDSA_HANDLER, missing_sigver_msg);
    RUN_TEST_CASE(APP_ECDSA_HANDLER, missing_sigver_r_s);
    RUN_TEST_CASE(APP_ECDSA_HANDLER, missing_sigver_qx_qy);
}

TEST_GROUP_RUNNER(APP_HMAC_HANDLER) {
    RUN_TEST_CASE(APP_HMAC_HANDLER, missing_msg);
    RUN_TEST_CASE(APP_HMAC_HANDLER, missing_key);
    RUN_TEST_CASE(APP_HMAC_HANDLER, disposition_mem_not_allocated);
}

TEST_GROUP_RUNNER(APP_KAS_ECC_HANDLER) {
    RUN_TEST_CASE(APP_KAS_ECC_HANDLER, invalid_curve);
    RUN_TEST_CASE(APP_KAS_ECC_HANDLER, invalid_hash_ecc_comp);
    RUN_TEST_CASE(APP_KAS_ECC_HANDLER, missing_psx);
    RUN_TEST_CASE(APP_KAS_ECC_HANDLER, missing_psy);
    RUN_TEST_CASE(APP_KAS_ECC_HANDLER, missing_pix);
    RUN_TEST_CASE(APP_KAS_ECC_HANDLER, missing_piy);
}

TEST_GROUP_RUNNER(APP_KAS_FFC_HANDLER) {
    RUN_TEST_CASE(APP_KAS_FFC_HANDLER, invalid_hash_alg);
    RUN_TEST_CASE(APP_KAS_FFC_HANDLER, missing_p);
    RUN_TEST_CASE(APP_KAS_FFC_HANDLER, missing_q);
    RUN_TEST_CASE(APP_KAS_FFC_HANDLER, missing_g);
    RUN_TEST_CASE(APP_KAS_FFC_HANDLER, missing_eps);
    RUN_TEST_CASE(APP_KAS_FFC_HANDLER, missing_epri);
    RUN_TEST_CASE(APP_KAS_FFC_HANDLER, missing_epui);
    RUN_TEST_CASE(APP_KAS_FFC_HANDLER, missing_z);
    RUN_TEST_CASE(APP_KAS_FFC_HANDLER, missing_dgm);
    RUN_TEST_CASE(APP_KAS_FFC_HANDLER, unallocated_ans_bufs);
}

TEST_GROUP_RUNNER(APP_KAS_IFC_HANDLER) {
    RUN_TEST_CASE(APP_KAS_IFC_HANDLER, invalid_hash_alg);
    RUN_TEST_CASE(APP_KAS_IFC_HANDLER, missing_server_e);
    RUN_TEST_CASE(APP_KAS_IFC_HANDLER, missing_server_n);
    RUN_TEST_CASE(APP_KAS_IFC_HANDLER, missing_iut_pt_z);
    RUN_TEST_CASE(APP_KAS_IFC_HANDLER, missing_buf_iut_ct_z);
    RUN_TEST_CASE(APP_KAS_IFC_HANDLER, missing_buf_iut_pt_z);
    RUN_TEST_CASE(APP_KAS_IFC_HANDLER, missing_e);
    RUN_TEST_CASE(APP_KAS_IFC_HANDLER, missing_n);
    RUN_TEST_CASE(APP_KAS_IFC_HANDLER, missing_p);
    RUN_TEST_CASE(APP_KAS_IFC_HANDLER, missing_q);
    RUN_TEST_CASE(APP_KAS_IFC_HANDLER, missing_d);
    RUN_TEST_CASE(APP_KAS_IFC_HANDLER, missing_ct);
    RUN_TEST_CASE(APP_KAS_IFC_HANDLER, missing_buf_serv_pt_z);
}

TEST_GROUP_RUNNER(APP_KDA_HKDF_HANDLER) {
    RUN_TEST_CASE(APP_KDA_HKDF_HANDLER, invalid_encoding);
    RUN_TEST_CASE(APP_KDA_HKDF_HANDLER, invalid_pattern);
    RUN_TEST_CASE(APP_KDA_HKDF_HANDLER, invalid_alg);
}

TEST_GROUP_RUNNER(APP_KDA_ONESTEP_HANDLER) {
    RUN_TEST_CASE(APP_KDA_ONESTEP_HANDLER, invalid_encoding);
    RUN_TEST_CASE(APP_KDA_ONESTEP_HANDLER, invalid_pattern);
    RUN_TEST_CASE(APP_KDA_ONESTEP_HANDLER, invalid_alg);
}

TEST_GROUP_RUNNER(APP_KDF108_HANDLER) {
    RUN_TEST_CASE(APP_KDF108_HANDLER, invalid_mode);
    RUN_TEST_CASE(APP_KDF108_HANDLER, invalid_mac_mode);
    RUN_TEST_CASE(APP_KDF108_HANDLER, invalid_counter_loc);
    RUN_TEST_CASE(APP_KDF108_HANDLER, missing_key_in);
    RUN_TEST_CASE(APP_KDF108_HANDLER, unallocated_ans_bufs);
}

TEST_GROUP_RUNNER(APP_KDF135_SSH_HANDLER) {
    RUN_TEST_CASE(APP_KDF135_SSH_HANDLER, invalid_hash_alg);
    RUN_TEST_CASE(APP_KDF135_SSH_HANDLER, missing_ssk);
    RUN_TEST_CASE(APP_KDF135_SSH_HANDLER, missing_hash_h);
    RUN_TEST_CASE(APP_KDF135_SSH_HANDLER, missing_session_id);
    RUN_TEST_CASE(APP_KDF135_SSH_HANDLER, unallocated_ans_bufs);
}

TEST_GROUP_RUNNER(APP_KDF_TLS12_HANDLER) {
    RUN_TEST_CASE(APP_KDF_TLS12_HANDLER, invalid_hash_alg);
    RUN_TEST_CASE(APP_KDF_TLS12_HANDLER, missing_pm_secret);
    RUN_TEST_CASE(APP_KDF_TLS12_HANDLER, missing_session_hash);
    RUN_TEST_CASE(APP_KDF_TLS12_HANDLER, missing_c_rnd);
    RUN_TEST_CASE(APP_KDF_TLS12_HANDLER, missing_s_rnd);
    RUN_TEST_CASE(APP_KDF_TLS12_HANDLER, unallocated_ans_bufs);
}

TEST_GROUP_RUNNER(APP_KMAC_HANDLER) {
    RUN_TEST_CASE(APP_KMAC_HANDLER, missing_msg);
    RUN_TEST_CASE(APP_KMAC_HANDLER, missing_key);
    RUN_TEST_CASE(APP_KMAC_HANDLER, missing_mac_mvt);
    RUN_TEST_CASE(APP_KMAC_HANDLER, missing_maclen);
    RUN_TEST_CASE(APP_KMAC_HANDLER, missing_customization);
    RUN_TEST_CASE(APP_KMAC_HANDLER, mem_not_allocated);
}

TEST_GROUP_RUNNER(APP_KTS_IFC_HANDLER) {
    RUN_TEST_CASE(APP_KTS_IFC_HANDLER, invalid_hash_alg);
    RUN_TEST_CASE(APP_KTS_IFC_HANDLER, invalid_modulo);
    RUN_TEST_CASE(APP_KTS_IFC_HANDLER, invalid_llen);
    RUN_TEST_CASE(APP_KTS_IFC_HANDLER, missing_e);
    RUN_TEST_CASE(APP_KTS_IFC_HANDLER, missing_n);
    RUN_TEST_CASE(APP_KTS_IFC_HANDLER, missing_p);
    RUN_TEST_CASE(APP_KTS_IFC_HANDLER, missing_q);
    RUN_TEST_CASE(APP_KTS_IFC_HANDLER, missing_d);
    RUN_TEST_CASE(APP_KTS_IFC_HANDLER, missing_ct);
    RUN_TEST_CASE(APP_KTS_IFC_HANDLER, unallocated_ans_bufs);
}

TEST_GROUP_RUNNER(APP_PBKDF_HANDLER) {
    RUN_TEST_CASE(APP_PBKDF_HANDLER, missing_test_case);
    RUN_TEST_CASE(APP_PBKDF_HANDLER, missing_pbkdf_tc);
    RUN_TEST_CASE(APP_PBKDF_HANDLER, missing_hmacAlg);
    RUN_TEST_CASE(APP_PBKDF_HANDLER, missing_salt);
    RUN_TEST_CASE(APP_PBKDF_HANDLER, missing_saltlen);
    RUN_TEST_CASE(APP_PBKDF_HANDLER, missing_password);
    RUN_TEST_CASE(APP_PBKDF_HANDLER, missing_pwlen);
    RUN_TEST_CASE(APP_PBKDF_HANDLER, missing_iteration);
    RUN_TEST_CASE(APP_PBKDF_HANDLER, missing_key);
    RUN_TEST_CASE(APP_PBKDF_HANDLER, missing_keylen);
}

TEST_GROUP_RUNNER(APP_RSA_KEYGEN_HANDLER) {
    RUN_TEST_CASE(APP_RSA_KEYGEN_HANDLER, invalid_hash_alg);
    RUN_TEST_CASE(APP_RSA_KEYGEN_HANDLER, invalid_key_format);
    RUN_TEST_CASE(APP_RSA_KEYGEN_HANDLER, invalid_pub_exp_mode);
    RUN_TEST_CASE(APP_RSA_KEYGEN_HANDLER, invalid_modulo);
    RUN_TEST_CASE(APP_RSA_KEYGEN_HANDLER, invalid_prime_test);
    RUN_TEST_CASE(APP_RSA_KEYGEN_HANDLER, invalid_rand_pq);
    RUN_TEST_CASE(APP_RSA_KEYGEN_HANDLER, missing_e);
    RUN_TEST_CASE(APP_RSA_KEYGEN_HANDLER, missing_seed);
    RUN_TEST_CASE(APP_RSA_KEYGEN_HANDLER, unallocated_ans_bufs);
}

TEST_GROUP_RUNNER(APP_RSA_SIG_HANDLER) {
    RUN_TEST_CASE(APP_RSA_SIG_HANDLER, invalid_hash_alg);
}

TEST_GROUP_RUNNER(APP_SAFE_PRIMES_HANDLER) {
    RUN_TEST_CASE(APP_SAFE_PRIMES_HANDLER, invalid_dgm);
    RUN_TEST_CASE(APP_SAFE_PRIMES_HANDLER, invalid_alg_id);
    RUN_TEST_CASE(APP_SAFE_PRIMES_HANDLER, unallocated_ans_bufs);
    // RUN_TEST_CASE(APP_SAFE_PRIMES_HANDLER, result);  // Disabled (in #if 0)
}

TEST_GROUP_RUNNER(APP_SHA_HANDLER) {
    RUN_TEST_CASE(APP_SHA_HANDLER, properly_sha1_8);
    RUN_TEST_CASE(APP_SHA_HANDLER, properly_sha1_22688);
    RUN_TEST_CASE(APP_SHA_HANDLER, missing_msg_sha1);
    RUN_TEST_CASE(APP_SHA_HANDLER, disposition_mem_not_allocated);
    RUN_TEST_CASE(APP_SHA_HANDLER, properly_sha224_8);
    RUN_TEST_CASE(APP_SHA_HANDLER, properly_sha224_32192);
    RUN_TEST_CASE(APP_SHA_HANDLER, properly_sha384_152);
    RUN_TEST_CASE(APP_SHA_HANDLER, properly_sha384_73888);
    RUN_TEST_CASE(APP_SHA_HANDLER, properly_sha512_112);
    RUN_TEST_CASE(APP_SHA_HANDLER, properly_sha384_37456);
}

TEST_GROUP_RUNNER(APP_TLS13_KDF_HANDLER) {
    RUN_TEST_CASE(APP_TLS13_KDF_HANDLER, invalid_runmode1);
    RUN_TEST_CASE(APP_TLS13_KDF_HANDLER, invalid_runmode2);
    RUN_TEST_CASE(APP_TLS13_KDF_HANDLER, invalid_runmode3);
    RUN_TEST_CASE(APP_TLS13_KDF_HANDLER, invalid_runmode4);
    RUN_TEST_CASE(APP_TLS13_KDF_HANDLER, invalid_hash_alg);
    RUN_TEST_CASE(APP_TLS13_KDF_HANDLER, missing_psk);
    RUN_TEST_CASE(APP_TLS13_KDF_HANDLER, missing_s_hello_rand);
    RUN_TEST_CASE(APP_TLS13_KDF_HANDLER, missing_c_hello_rand);
    RUN_TEST_CASE(APP_TLS13_KDF_HANDLER, missing_fin_c_hello_rand);
    RUN_TEST_CASE(APP_TLS13_KDF_HANDLER, missing_fin_s_hello_rand);
    RUN_TEST_CASE(APP_TLS13_KDF_HANDLER, unallocated_ans_bufs);
}

// Function to run all APP tests
void run_app_tests(void) {
    RUN_TEST_GROUP(APP_AES_AEAD_HANDLER);
    RUN_TEST_GROUP(APP_AES_HANDLER);
    RUN_TEST_GROUP(APP_AES_KW_HANDLER);
    RUN_TEST_GROUP(APP_CMAC_HANDLER);
    RUN_TEST_GROUP(APP_DES_HANDLER);
    RUN_TEST_GROUP(APP_DRBG_HANDLER);
    RUN_TEST_GROUP(APP_ECDSA_HANDLER);
    RUN_TEST_GROUP(APP_HMAC_HANDLER);
    RUN_TEST_GROUP(APP_KAS_ECC_HANDLER);
    RUN_TEST_GROUP(APP_KAS_FFC_HANDLER);
    RUN_TEST_GROUP(APP_KAS_IFC_HANDLER);
    RUN_TEST_GROUP(APP_KDA_HKDF_HANDLER);
    RUN_TEST_GROUP(APP_KDA_ONESTEP_HANDLER);
    RUN_TEST_GROUP(APP_KDF108_HANDLER);
    RUN_TEST_GROUP(APP_KDF135_SSH_HANDLER);
    RUN_TEST_GROUP(APP_KDF_TLS12_HANDLER);
    RUN_TEST_GROUP(APP_KMAC_HANDLER);
    RUN_TEST_GROUP(APP_KTS_IFC_HANDLER);
    RUN_TEST_GROUP(APP_PBKDF_HANDLER);
    RUN_TEST_GROUP(APP_RSA_KEYGEN_HANDLER);
    RUN_TEST_GROUP(APP_RSA_SIG_HANDLER);
    RUN_TEST_GROUP(APP_SAFE_PRIMES_HANDLER);
    RUN_TEST_GROUP(APP_SHA_HANDLER);
    RUN_TEST_GROUP(APP_TLS13_KDF_HANDLER);
}
